name: Auto Upload

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: aiarena/arenaclient #debian:bookworm #aiarena/arenaclient
    steps:
    - uses: actions/checkout@v4

#    - name: Install dependencies
#      run: apt-get update && apt-get upgrade --assume-yes --quiet=2 && apt-get install --assume-yes --no-install-recommends --no-show-upgraded cmake gnupg2 wget make git procps g++ ffmpeg libsm6 libxext6 unzip && rm -rf /var/lib/apt/lists/* && update-ca-certificates

    - name: Install dependencies
      run: apt-get update && apt-get upgrade --assume-yes --quiet=2 && apt-get install --assume-yes --no-install-recommends --no-show-upgraded cmake make g++ binutils-dev libiberty-dev libzstd-dev && apt-get install apt-transport-https ca-certificates -y && update-ca-certificates

    - name: Config
      run: cmake -B build -DBUILD_FOR_LADDER=ON -DSC2_VERSION=4.10.0

    - name: Build
      run: cmake --build build --parallel 6

    - name: Upload
      run: python3 upload.py
